//
// File generated by rootcint at Wed Oct  5 18:42:38 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictp349_data
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dictp349_data.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void P349_data_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_P349_data(void *p = 0);
   static void *newArray_P349_data(Long_t size, void *p);
   static void delete_P349_data(void *p);
   static void deleteArray_P349_data(void *p);
   static void destruct_P349_data(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::P349_data*)
   {
      ::P349_data *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::P349_data >(0);
      static ::ROOT::TGenericClassInfo 
         instance("P349_data", ::P349_data::Class_Version(), "./P349_data.h", 41,
                  typeid(::P349_data), ::ROOT::DefineBehavior(ptr, ptr),
                  &::P349_data::Dictionary, isa_proxy, 4,
                  sizeof(::P349_data) );
      instance.SetNew(&new_P349_data);
      instance.SetNewArray(&newArray_P349_data);
      instance.SetDelete(&delete_P349_data);
      instance.SetDeleteArray(&deleteArray_P349_data);
      instance.SetDestructor(&destruct_P349_data);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::P349_data*)
   {
      return GenerateInitInstanceLocal((::P349_data*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::P349_data*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr P349_data::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *P349_data::Class_Name()
{
   return "P349_data";
}

//______________________________________________________________________________
const char *P349_data::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::P349_data*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int P349_data::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::P349_data*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void P349_data::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::P349_data*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *P349_data::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::P349_data*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void P349_data::Streamer(TBuffer &R__b)
{
   // Stream an object of class P349_data.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(P349_data::Class(),this);
   } else {
      R__b.WriteClassBuffer(P349_data::Class(),this);
   }
}

//______________________________________________________________________________
void P349_data::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class P349_data.
      TClass *R__cl = ::P349_data::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "globalchan", &globalchan);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trb", &trb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdc", &tdc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chan", &chan);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "edge", &edge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "realtime", &realtime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tottime", &tottime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "detector", &detector);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "detectorlayer", &detectorlayer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "layerelement", &layerelement);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_P349_data(void *p) {
      return  p ? new(p) ::P349_data : new ::P349_data;
   }
   static void *newArray_P349_data(Long_t nElements, void *p) {
      return p ? new(p) ::P349_data[nElements] : new ::P349_data[nElements];
   }
   // Wrapper around operator delete
   static void delete_P349_data(void *p) {
      delete ((::P349_data*)p);
   }
   static void deleteArray_P349_data(void *p) {
      delete [] ((::P349_data*)p);
   }
   static void destruct_P349_data(void *p) {
      typedef ::P349_data current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::P349_data

/********************************************************
* dictp349_data.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledictp349_data();

extern "C" void G__set_cpp_environmentdictp349_data() {
  G__cpp_reset_tagtabledictp349_data();
}
#include <new>
extern "C" int G__cpp_dllrevdictp349_data() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* P349_data */
static int G__dictp349_data_747_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   P349_data* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new P349_data[n];
     } else {
       p = new((void*) gvp) P349_data[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new P349_data;
     } else {
       p = new((void*) gvp) P349_data;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictp349_dataLN_P349_data));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   P349_data* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 10
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new P349_data(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (int) G__int(libp->para[7])
, (int) G__int(libp->para[8]), (int) G__int(libp->para[9]));
   } else {
     p = new((void*) gvp) P349_data(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (int) G__int(libp->para[7])
, (int) G__int(libp->para[8]), (int) G__int(libp->para[9]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictp349_dataLN_P349_data));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   P349_data* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 9
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new P349_data(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (int) G__int(libp->para[6]), (int) G__int(libp->para[7])
, (int) G__int(libp->para[8]));
   } else {
     p = new((void*) gvp) P349_data(
(int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (int) G__int(libp->para[6]), (int) G__int(libp->para[7])
, (int) G__int(libp->para[8]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictp349_dataLN_P349_data));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   P349_data* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new P349_data(*(P349_data*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) P349_data(*(P349_data*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictp349_dataLN_P349_data));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const P349_data& obj = ((P349_data*) G__getstructoffset())->operator=(*(P349_data*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetGlobalchan((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetTrb((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetTdc((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetChan((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetEdge((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetRealtime((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetTottime((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetDetector((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetDetectorlayer((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->SetLayerelement((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetGlobalchan());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetTrb());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetTdc());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetChan());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetEdge());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const P349_data*) G__getstructoffset())->GetRealtime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const P349_data*) G__getstructoffset())->GetTottime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetDetector());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetDetectorlayer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const P349_data*) G__getstructoffset())->GetLayerelement());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) P349_data::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) P349_data::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) P349_data::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      P349_data::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((P349_data*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) P349_data::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) P349_data::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) P349_data::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictp349_data_747_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) P349_data::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef P349_data G__TP349_data;
static int G__dictp349_data_747_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (P349_data*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((P349_data*) (soff+(sizeof(P349_data)*i)))->~G__TP349_data();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (P349_data*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((P349_data*) (soff))->~G__TP349_data();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* P349_data */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdictp349_data {
 public:
  G__Sizep2memfuncdictp349_data(): p(&G__Sizep2memfuncdictp349_data::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdictp349_data::*p)();
};

size_t G__get_sizep2memfuncdictp349_data()
{
  G__Sizep2memfuncdictp349_data a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedictp349_data() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictp349_dataLN_P349_data))) {
     P349_data *G__Lderived;
     G__Lderived=(P349_data*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictp349_dataLN_P349_data),G__get_linked_tagnum(&G__dictp349_dataLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledictp349_data() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictp349_dataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictp349_dataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictp349_dataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictp349_dataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictp349_dataLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictp349_dataLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__dictp349_dataLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* P349_data */
static void G__setup_memvarP349_data(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictp349_dataLN_P349_data));
   { P349_data *p; p=(P349_data*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"globalchan=",0,"Global Channel Number");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"trb=",0,"TRB Board Number");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"tdc=",0,"TDC Number ");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"chan=",0,"Channel Number");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"edge=",0,"Edge Marker, 1 Leading, 0 Trailing only valid for 2015+ data");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"realtime=",0,"Realtime");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"tottime=",0,"Time over Treshold");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"detector=",0,"Detectornumber");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"detectorlayer=",0,"Number of Detectorlayer");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"layerelement=",0,"Elementnumber");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictp349_dataLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardictp349_data() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncP349_data(void) {
   /* P349_data */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictp349_dataLN_P349_data));
   G__memfunc_setup("P349_data",745,G__dictp349_data_747_0_1, 105, G__get_linked_tagnum(&G__dictp349_dataLN_P349_data), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("P349_data",745,G__dictp349_data_747_0_2, 105, G__get_linked_tagnum(&G__dictp349_dataLN_P349_data), -1, 0, 10, 1, 1, 0, 
"i - - 0 - - i - - 0 - - "
"i - - 0 - - i - - 0 - - "
"i - - 0 - - d - - 0 - - "
"d - - 0 - - i - - 0 - - "
"i - - 0 - - i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("P349_data",745,G__dictp349_data_747_0_3, 105, G__get_linked_tagnum(&G__dictp349_dataLN_P349_data), -1, 0, 9, 1, 1, 0, 
"i - - 0 - - i - - 0 - - "
"i - - 0 - - i - - 0 - - "
"d - - 0 - - d - - 0 - - "
"i - - 0 - - i - - 0 - - "
"i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("P349_data",745,G__dictp349_data_747_0_4, 105, G__get_linked_tagnum(&G__dictp349_dataLN_P349_data), -1, 0, 1, 1, 1, 0, "u 'P349_data' - 41 - other", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__dictp349_data_747_0_5, 117, G__get_linked_tagnum(&G__dictp349_dataLN_P349_data), -1, 1, 1, 1, 1, 0, "u 'P349_data' - 41 - other", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGlobalchan",1303,G__dictp349_data_747_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrb",596,G__dictp349_data_747_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTdc",583,G__dictp349_data_747_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChan",678,G__dictp349_data_747_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEdge",673,G__dictp349_data_747_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRealtime",1119,G__dictp349_data_747_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTottime",1042,G__dictp349_data_747_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDetector",1126,G__dictp349_data_747_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDetectorlayer",1667,G__dictp349_data_747_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLayerelement",1555,G__dictp349_data_747_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newval", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGlobalchan",1291,G__dictp349_data_747_0_16, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrb",584,G__dictp349_data_747_0_17, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTdc",571,G__dictp349_data_747_0_18, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChan",666,G__dictp349_data_747_0_19, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEdge",661,G__dictp349_data_747_0_20, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRealtime",1107,G__dictp349_data_747_0_21, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTottime",1030,G__dictp349_data_747_0_22, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDetector",1114,G__dictp349_data_747_0_23, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDetectorlayer",1655,G__dictp349_data_747_0_24, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLayerelement",1543,G__dictp349_data_747_0_25, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("copy",443,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'P349_data' - 41 - other", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("destroy",778,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dictp349_data_747_0_28, 85, G__get_linked_tagnum(&G__dictp349_dataLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&P349_data::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictp349_data_747_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&P349_data::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictp349_data_747_0_30, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&P349_data::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictp349_data_747_0_31, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&P349_data::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictp349_dataLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictp349_data_747_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictp349_data_747_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&P349_data::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictp349_data_747_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&P349_data::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictp349_data_747_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&P349_data::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictp349_data_747_0_39, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&P349_data::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~P349_data", 871, G__dictp349_data_747_0_40, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdictp349_data() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldictp349_data() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdictp349_data() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictp349_dataLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__dictp349_dataLN_P349_data = { "P349_data" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledictp349_data() {
  G__dictp349_dataLN_TClass.tagnum = -1 ;
  G__dictp349_dataLN_TBuffer.tagnum = -1 ;
  G__dictp349_dataLN_TMemberInspector.tagnum = -1 ;
  G__dictp349_dataLN_TObject.tagnum = -1 ;
  G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictp349_dataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictp349_dataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__dictp349_dataLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__dictp349_dataLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__dictp349_dataLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictp349_dataLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__dictp349_dataLN_P349_data.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledictp349_data() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictp349_dataLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictp349_dataLN_P349_data),sizeof(P349_data),-1,327424,(char*)NULL,G__setup_memvarP349_data,G__setup_memfuncP349_data);
}
extern "C" void G__cpp_setupdictp349_data(void) {
  G__check_setup_version(30051515,"G__cpp_setupdictp349_data()");
  G__set_cpp_environmentdictp349_data();
  G__cpp_setup_tagtabledictp349_data();

  G__cpp_setup_inheritancedictp349_data();

  G__cpp_setup_typetabledictp349_data();

  G__cpp_setup_memvardictp349_data();

  G__cpp_setup_memfuncdictp349_data();
  G__cpp_setup_globaldictp349_data();
  G__cpp_setup_funcdictp349_data();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdictp349_data();
  return;
}
class G__cpp_setup_initdictp349_data {
  public:
    G__cpp_setup_initdictp349_data() { G__add_setup_func("dictp349_data",(G__incsetup)(&G__cpp_setupdictp349_data)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdictp349_data() { G__remove_setup_func("dictp349_data"); }
};
G__cpp_setup_initdictp349_data G__cpp_setup_initializerdictp349_data;

