/********************************************************************
* dictp349_data.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dictp349_data.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictp349_data();
extern void G__cpp_setup_inheritancedictp349_data();
extern void G__cpp_setup_typetabledictp349_data();
extern void G__cpp_setup_memvardictp349_data();
extern void G__cpp_setup_globaldictp349_data();
extern void G__cpp_setup_memfuncdictp349_data();
extern void G__cpp_setup_funcdictp349_data();
extern void G__set_cpp_environmentdictp349_data();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "P349_data.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictp349_dataLN_TClass;
extern G__linked_taginfo G__dictp349_dataLN_TBuffer;
extern G__linked_taginfo G__dictp349_dataLN_TMemberInspector;
extern G__linked_taginfo G__dictp349_dataLN_TObject;
extern G__linked_taginfo G__dictp349_dataLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictp349_dataLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictp349_dataLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictp349_dataLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictp349_dataLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictp349_dataLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__dictp349_dataLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dictp349_dataLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__dictp349_dataLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__dictp349_dataLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictp349_dataLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__dictp349_dataLN_P349_data;

/* STUB derived class for protected member access */
